name: Lint

on:
  workflow_call:
    inputs:
      package_path:
        type: string
        required: false
        default: './'
        description: "Specifies a subpath of the checkout that the package is contained in."

jobs:
  format:
    name: Format linting
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Format
      run: |
        swift format lint \
          --parallel \
          --recursive \
          ${{ inputs.package_path != './' && inputs.package_path || './' }}
