name: Lint

on:
  workflow_call:
    inputs:
      package_path:
        type: string
        required: false
        default: ''
        description: "Specifies a subpath of the checkout that the package is contained in."

jobs:
  format:
    name: Format linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Pull formatting docker image
        run: docker pull ghcr.io/nicklockwood/swiftformat:latest
      - name: Run format linting
        run: docker run --rm -v ${{ github.workspace }}:/repo ghcr.io/nicklockwood/swiftformat:latest /repo/${{ inputs.package_path }} --lint
