name: Test

on:
  workflow_call:
    inputs:
      package_path:
        type: string
        required: false
        default: ''
        description: "Specifies a subpath of the checkout that the package is contained in."
      include_android:
        type: boolean
        description: "Whether testing should include an Android target."
        default: true

env:
  PACKAGE_PATH: ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

jobs:
  macos:
    name: Test on macOS - ${{ matrix.swift-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        swift-version:
          - "6.2"
          - "6.3"
          - "6.4"
    steps:
    - uses: swift-actions/setup-swift@v3
      with:
        swift-version: ${{ matrix.swift-version }}
    - uses: actions/checkout@v4
    - name: Build and test
      run: |
        swift test \
          ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

  linux:
    name: Test on Linux - ${{ matrix.swift-tag }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-tag:
          - "6.2"
          - "6.3"
          - "6.4"
    container: "swift:${{ matrix.swift-tag }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test \
          ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

  android:
    name: Test on Android
    if: ${{ inputs.include_android }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      uses: skiptools/swift-android-action@v2
      with:
        package-path: ${{ inputs.package_path != '' && inputs.package_path || '.' }}
