name: Test

on:
  workflow_call:
    inputs:
      package_path:
        type: string
        required: false
        default: ''
        description: "Specifies a subpath of the checkout that the package is contained in."

env:
  PACKAGE_PATH: ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

jobs:
  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Build and test
      run: |
        swift test \
          --parallel \
          ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v2
    - uses: actions/checkout@v4
    - name: Test
      run: |
        swift test \
          --parallel \
          ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}

  android:
    name: Test on Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test
      uses: skiptools/swift-android-action@v2
      with:
        package-path: ${{ inputs.package_path != '' && inputs.package_path || '.' }}

  backcompat-ubuntu-22_04:
    name: Test Swift ${{ matrix.swift }} on Ubuntu 22.04
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        swift: ["5.8", "5.9", "5.10", "6.0"]
    steps:
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v4
    - name: Test
      run: |
        swift test \
          --parallel \
          ${{ inputs.package_path != '' && format('--package-path={0}', inputs.package_path) || '' }}
